// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: TempControlPID

#ifndef _TEMPCONTROLPID_UI_H
#define _TEMPCONTROLPID_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label4;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel1;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Image9;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel4;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Image3;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label2;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Image2;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Chart1_Xaxis;
extern lv_obj_t * ui_Chart1_Yaxis1;
extern lv_obj_t * ui_Chart1_Yaxis2;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui____initial_actions0;
extern lv_chart_series_t * ui_Chart1_series_1;


LV_IMG_DECLARE(ui_img_thermostat_png);    // assets/thermostat.png
LV_IMG_DECLARE(ui_img_graphico_png);    // assets/graphico.png
LV_IMG_DECLARE(ui_img_down1_png);    // assets/down1.png
LV_IMG_DECLARE(ui_img_motin_png);    // assets/motin.png
LV_IMG_DECLARE(ui_img_minimize_png);    // assets/minimize.png
LV_IMG_DECLARE(ui_img_down_png);    // assets/down.png
LV_IMG_DECLARE(ui_img_1486996648);    // assets/up-arrow.png
LV_IMG_DECLARE(ui_img_backa_png);    // assets/backA.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
