// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: TempControlPID

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void StepUp(lv_event_t * e);
void StepDown(lv_event_t * e);
void setTemp(lv_event_t * e);
void decrease(lv_event_t * e);
void increase(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
