// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: TempControlPID

#include "ui.h"

void StepUp(lv_event_t * e)
{
	// Your code here
}

void StepDown(lv_event_t * e)
{
	// Your code here
}

void setTemp(lv_event_t * e)
{
	// Your code here
}

void decrease(lv_event_t * e)
{
	// Your code here
}

void increase(lv_event_t * e)
{
	// Your code here
}
